# Generated by Django 4.1.4 on 2022-12-14 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255)),
                ('number_of_days_trip', models.SmallIntegerField()),
                ('place_image', models.ImageField(upload_to='tripPlace')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.CharField(max_length=11)),
                ('activity_place_name', models.CharField(max_length=255)),
                ('activity_place_description', models.CharField(max_length=255)),
                ('activity_place_image', models.ImageField(upload_to='activityPlaces')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tripplace')),
            ],
        ),
    ]
