# Generated by Django 4.1.4 on 2022-12-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_activity_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_place_description',
            field=models.TextField(max_length=255),
        ),
    ]
