# Generated by Django 4.1.4 on 2022-12-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activity_activity_place_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_place_description',
            field=models.TextField(),
        ),
    ]
