# Generated by Django 4.1.4 on 2022-12-17 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_activity_place_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.RemoveField(
            model_name='tripplace',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tripplace',
            name='start_date',
        ),
        migrations.AddField(
            model_name='tripplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
    ]
