# Generated by Django 4.1.4 on 2022-12-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_activity_date_remove_activity_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='day_number',
        ),
    ]
